// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Svabic.Api.Podaci;

#nullable disable

namespace Svabic.Api.Podaci.Migracije
{
    [DbContext(typeof(SvabicDbContext))]
    [Migration("20260929094831_VrstePapagaja")]
    partial class VrstePapagaja
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Svabic.Api.Domen.Kategorija", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Redosled")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Kategorije");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Pakovanje", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivno")
                        .HasColumnType("boolean");

                    b.Property<int>("CenaRsd")
                        .HasColumnType("integer");

                    b.Property<string>("Oznaka")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PostarinaRsd")
                        .HasColumnType("integer");

                    b.Property<int>("ProizvodId")
                        .HasColumnType("integer");

                    b.Property<int>("Redosled")
                        .HasColumnType("integer");

                    b.Property<int?>("TezinaGrama")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProizvodId");

                    b.ToTable("Pakovanja");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Proizvod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("Aktivan")
                        .HasColumnType("boolean");

                    b.Property<bool>("JeZaAre")
                        .HasColumnType("boolean");

                    b.Property<int>("KategorijaId")
                        .HasColumnType("integer");

                    b.Property<string>("KratakOpis")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Redosled")
                        .HasColumnType("integer");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("KategorijaId");

                    b.ToTable("Proizvodi");
                });

            modelBuilder.Entity("Svabic.Api.Domen.VrstaPapagaja", b =>
                {
                    b.Property<string>("Slug")
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<bool>("Aktivna")
                        .HasColumnType("boolean");

                    b.Property<int>("DanaPoKg")
                        .HasColumnType("integer");

                    b.Property<string>("Naziv")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Redosled")
                        .HasColumnType("integer");

                    b.HasKey("Slug");

                    b.ToTable("Vrste");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Pakovanje", b =>
                {
                    b.HasOne("Svabic.Api.Domen.Proizvod", "Proizvod")
                        .WithMany("Pakovanja")
                        .HasForeignKey("ProizvodId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Proizvod");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Proizvod", b =>
                {
                    b.HasOne("Svabic.Api.Domen.Kategorija", "Kategorija")
                        .WithMany("Proizvodi")
                        .HasForeignKey("KategorijaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kategorija");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Kategorija", b =>
                {
                    b.Navigation("Proizvodi");
                });

            modelBuilder.Entity("Svabic.Api.Domen.Proizvod", b =>
                {
                    b.Navigation("Pakovanja");
                });
#pragma warning restore 612, 618
        }
    }
}
